backend login
byte-us/flitter-backend pull request #14
Opened 2023-02-10 19:45 UTC by emilyjheredia

2023-02-11 03:16 UTC, sarainesgonz requested changes
hay algunos conflictos, 
al hacer el post llega hasta la db

2023-02-11 14:12 UTC, stasy-sys commented
Te devuelva token JWT? No conseguí que me funciona en esta branch

2023-02-11 14:17 UTC, emilyjheredia commented
No use JWT use la libreria passport

2023-02-11 14:33 UTC, stasy-sys commented
Uhm, pero la libreria passport soporta JWT. Frontend necesita un token para poder logearse. No es eso lo que teníamos que hacer?

2023-02-11 14:38 UTC, emilyjheredia commented
dejame mirarlo

2023-02-11 14:45 UTC, stasy-sys commented
Check out this:
https://medium.com/front-end-weekly/learn-using-jwt-with-passport-authentication-9761539c4314

2023-02-12 12:44 UTC, emilyjheredia reviewed
rechazen este pull por favor

2023-02-12 16:30 UTC, closed without merging